name: Crystal Beasley
description: excited and terrified, just like I like it
url: crystalbeasley.com
baseurl: /

markdown: rdiscount

permalink: /:year/:month/:day/:title
lsi: false

exclude:
- CNAME
- README.md
- /scss/